// <auto-generated />
using MapParcel_son.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MapParcel_son.Migrations
{
    [DbContext(typeof(ParcelContext))]
    [Migration("20220126071829_MapParcel")]
    partial class MapParcel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("MapParcel_son.Models.ParcelModel", b =>
                {
                    b.Property<int>("ParcelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ParcelCity")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("ParcelCountry")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("ParcelDistrict")
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<string>("WktString")
                        .HasColumnType("text")
                        .HasColumnName("wkt");

                    b.HasKey("ParcelID");

                    b.ToTable("parcels");
                });
#pragma warning restore 612, 618
        }
    }
}
